### ISSUE TITLE
About Dependencies of LAS

### ISSUE THREAD

**Issue by goodtaeeun** [thwak/LAS#2]
Hello, I am a Undergrad. student studying APR.

I was interested in your paper about ConFix and was trying to modify it.
Since Confix uses LAS to prepare the change pool, I also tried to use LAS.

After I built LAS with maven, I tried to run the program with the following command.
* note I changed "main.LAS" to "main.TreeDiff" because the class with the main method is not LAS, but TreeDiff in current version.

~~~bash
goodt@ubuntu:~/LAS/target$ java -cp ./LAS-0.0.1-SNAPSHOT.jar main.TreeDiff ../lang-old.java ../lang-new.java
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jdt/core/dom/ASTVisitor
        at main.TreeDiff.main(TreeDiff.java:40)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.core.dom.ASTVisitor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 1 more
~~~

However it resulted in above error.

It seems like org.eclipse.jdt.core.dom is not imported successfully, thus not being able to create AST from the given source file.

Did this problem also happen in your case? If not, do you have any suggestions to solve this problem?

I tried to figure out a way to add the dependency in the pom.xml, but failed to find a solution.

My environment is as follows
~~~bash
goodt@ubuntu:~/ConFix/lib$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

goodt@ubuntu:~/ConFix/lib$ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

goodt@ubuntu:~/ConFix/lib$ mvn --v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/goodt/paths/apache-maven-3.6.3
Java version: 1.8.0_261, vendor: Oracle Corporation, runtime: /home/goodt/paths/jdk1.8.0_261/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-48-generic", arch: "amd64", family: "unix"

~~~

With all the respect,
Kim.

**Comment by thwak** [comment]
This shouldn't have happened when Eclipse JDT(eclipse.jdt.core) dependency was resolved.
When you build LAS with Maven using `mvn build` or `mvn package`, it is automatically downloading necessary dependencies from repositories.

I'm pretty sure that Eclipse JDT core is included in the Central repository `https://repo1.maven.org/maven2/`.
You may wanna double check your `settings.xml` of Maven for the repository.

Or you can add the repository in `pom.xml` of LAS.

Jindae

**Comment by goodtaeeun** [comment]
Thank you for your reply!

So this shouldn't be a problem if things are set right.
I will try to resolve this problem with your advice.

Best wishes,
Kim.
